[package]
name = "hashpression"
version = "0.1.0"
authors = ["ben"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# fnv = "1.0.7"
hash32 = "0.1.1"
bincode = "1.3.1"
